### ISSUE TITLE
Broken PoolingHttpClientConnectionManager causing "Received fatal alert: bad_certificate" on Bot Certificate Authentication

### ISSUE THREAD

**Issue by wngasinur** [finos/symphony-bdk-java#519]
## Bug Report
🐛 

### Steps to Reproduce:
1. Have imported the right trust store
2. Using bot certificate authentication
3. Run bot as usual

### Expected Result:
Bot should run without any issue

### Actual Result:

Unable to run the bot with the certificate authentication.
Stacktrace :
`Caused by: java.lang.RuntimeException: Network error occurred while trying to connect to the "SESSION_AUTH" at the following address: https://---/sessionauth. Error while trying to validate certificate for the trust store. This type of error typically means that your network is using a self-signed certificate.
	at com.symphony.bdk.core.auth.impl.AuthenticationRetry.executeAndRetry(AuthenticationRetry.java:92)
	at com.symphony.bdk.core.auth.impl.AbstractBotAuthenticator.retrieveToken(AbstractBotAuthenticator.java:28)
	at com.symphony.bdk.core.auth.impl.BotAuthenticatorCertImpl.retrieveSessionToken(BotAuthenticatorCertImpl.java:54)
	at com.symphony.bdk.core.auth.impl.AuthSessionCertImpl.refresh(AuthSessionCertImpl.java:44)
	at com.symphony.bdk.core.auth.impl.BotAuthenticatorCertImpl.authenticateBot(BotAuthenticatorCertImpl.java:47)
	at com.symphony.bdk.core.SymphonyBdk.<init>(SymphonyBdk.java:110)
	at com.symphony.bdk.core.SymphonyBdk.<init>(SymphonyBdk.java:85)
	at flo.iflow.bot.engine.service.SymphonyBotService.init(SymphonyBotService.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 31 common frames omitted
Caused by: javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate`

Log from javax.net.debug : 
`
javax.net.ssl|FINE|01|main|2021-05-25 13:36:13.569 SGT|CertificateMessage.java:297|No X.509 certificate for client authentication, use empty Certificate message instead
javax.net.ssl|FINE|01|main|2021-05-25 13:36:13.569 SGT|CertificateMessage.java:328|Produced client Certificate handshake message (
"Certificates": <empty list>
)`

### Environment:
`>= BDK 2.1.3`

### Additional Context:
The stacktrace above is quite misleading also, saying there is an issue with our trust store, but in fact nothing wrong with our trust store.
The recent changes by introducing `PoolingHttpClientConnectionManager` on `ApiClientBuilderJersey2 ` is breaking SSL bot certificate authentication. 
The pool is constructed without proper SSLContext, it causes the private certificate file which configured by the symphony bdk is not being pickup during the API invocation.
Reference :
https://github.com/finos/symphony-bdk-java/pull/430

**Comment by symphony-youness** [comment]
Hi @wngasinur ,
We created an internal issue for this and we will update this as soon as we have a fix.

**Comment by symphony-thibault** [comment]
Hi @wngasinur, 

Certificate authentication is still working fine on our side with latest [2.1.8](https://github.com/finos/symphony-bdk-java/releases/tag/2.1.8) release. 

We however managed to reproduce your issue when revoking the CA from ACP: 
![Screen Shot 2021-06-11 at 16 51 38](https://user-images.githubusercontent.com/39826516/121705875-623de380-cad5-11eb-8041-51fde7043966.png)
Here's the stacktrace I obtained: 
```
16:49:38.609 [main] ERROR com.symphony.bdk.core.retry.RetryWithRecovery - Network error occurred while trying to connect to the "SESSION_AUTH" at the following address: https://localhost.symphony.com:8444/sessionauth. Error while trying to validate certificate for the trust store. This type of error typically means that your network is using a self-signed certificate.javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
Exception in thread "main" java.lang.RuntimeException: Network error occurred while trying to connect to the "SESSION_AUTH" at the following address: https://localhost.symphony.com:8444/sessionauth. Error while trying to validate certificate for the trust store. This type of error typically means that your network is using a self-signed certificate.
	at com.symphony.bdk.core.auth.impl.AuthenticationRetry.executeAndRetry(AuthenticationRetry.java:92)
	at com.symphony.bdk.core.auth.impl.AbstractBotAuthenticator.retrieveToken(AbstractBotAuthenticator.java:28)
	at com.symphony.bdk.core.auth.impl.BotAuthenticatorCertImpl.retrieveSessionToken(BotAuthenticatorCertImpl.java:54)
	at com.symphony.bdk.core.auth.impl.AuthSessionCertImpl.refresh(AuthSessionCertImpl.java:44)
	at com.symphony.bdk.core.auth.impl.BotAuthenticatorCertImpl.authenticateBot(BotAuthenticatorCertImpl.java:47)
	at com.symphony.bdk.core.SymphonyBdk.<init>(SymphonyBdk.java:110)
	at com.symphony.bdk.core.SymphonyBdk.<init>(SymphonyBdk.java:85)
	at com.symphony.bdk.BotApplication.main(BotApplication.java:27)
Caused by: javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:268)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:662)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:661)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:439)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:345)
	at com.symphony.bdk.http.jersey2.ApiClientJersey2.getResponse(ApiClientJersey2.java:179)
	at com.symphony.bdk.http.jersey2.ApiClientJersey2.invokeAPI(ApiClientJersey2.java:135)
	at com.symphony.bdk.gen.api.CertificateAuthenticationApi.v1AuthenticatePostWithHttpInfo(CertificateAuthenticationApi.java:411)
	at com.symphony.bdk.gen.api.CertificateAuthenticationApi.v1AuthenticatePost(CertificateAuthenticationApi.java:364)
	at com.symphony.bdk.core.auth.impl.BotAuthenticatorCertImpl.authenticateAndGetToken(BotAuthenticatorCertImpl.java:65)
	at com.symphony.bdk.core.auth.impl.AbstractBotAuthenticator.lambda$retrieveToken$0(AbstractBotAuthenticator.java:29)
	at com.symphony.bdk.core.retry.RetryWithRecovery.executeOnce(RetryWithRecovery.java:105)
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$3f69f149$1(Retry.java:137)
	at io.github.resilience4j.retry.Retry.executeCheckedSupplier(Retry.java:419)
	at com.symphony.bdk.core.retry.resilience4j.Resilience4jRetryWithRecovery.execute(Resilience4jRetryWithRecovery.java:65)
	at com.symphony.bdk.core.auth.impl.AuthenticationRetry.executeAndRetry(AuthenticationRetry.java:85)
	... 7 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:311)
	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:149)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1143)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1054)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:394)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:377)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:266)
	... 30 more
```
Could you please verify if the certificate you are using is correct?

**Comment by wngasinur** [comment]
Hi,
I dont have access to admin page, so revoking CA is not something I can do.
 I'm using the right certificate, when we downgraded to bdk 2.0.0 the issue with certificate is not there.

**Comment by symphony-thibault** [comment]
Hi @wngasinur, 

We are still unable to reproduce your issue. Would you please be able to provide a quick sample project (**without credentials**) that would help us reproducing it? 

From the stacktrace you provided, I see that you are using the `SymphonyBdk` from a SpringBoot application. Have considered using our [BDK Spring Boot Starter](https://github.com/finos/symphony-bdk-java/blob/main/docs/spring-boot/core-starter.md)?

**Comment by wngasinur** [comment]
@symphony-thibault ,

I can't really share the project here, but i'll share the snippet code here:

application.yml
```
bot:
  username: ***md21m
  certificate:
    path: ./***md21m.p12
    password: ***
agent:
  host: symphony-uat-agent.***.net
  port: 8444
keyManager:
  host: symphony-uat-km.***.net
  port: 8444
sessionAuth:
  host: symphony-uat-api.***.net
  port: 443
pod:
  host: symphony-uat-agent.***.net
  port: 8444
proxy:
  host: ***-proxy.***.net
  port: 8080
datafeed:
  idFilePath: ./
```

```
BdkConfig bdkConfig = BdkConfigLoader.loadFromClasspath("/application.yml");
SymphonyBdk bdk = new SymphonyBdk(bdkConfig); 
```

With this min setup, I'm able to run the bot with version 2.0.0, but once I upgraded to 2.1.x - 2.1.8.. I'm getting the SSL issue.

So the workaround I did, I've overridden function createClientConfig inside ApiClientBuilderJersey2 to initialize proper sslContext for PoolingHttpClientConnectionManager.

ApiClientBuilderJersey2
```

protected ClientConfig createClientConfig() {
...
SSLContext sslContext = createSSLContext();
        SSLConnectionSocketFactory sslConnectionSocketFactory = new SSLConnectionSocketFactory(sslContext,
                new String[]{"TLSv1.1", "TLSv1.2"}, null, SSLConnectionSocketFactory.getDefaultHostnameVerifier());
        Registry<ConnectionSocketFactory> registry = RegistryBuilder.<ConnectionSocketFactory>create()
                .register("https", sslConnectionSocketFactory)
                .register("http", new PlainConnectionSocketFactory())
                .build();

        PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager(registry);
...
}

```

**Comment by symphony-youri** [comment]
Thanks for the extra details!

I finally understood why I was not able to reproduce it, the Apache HTTP connection pool is effectively used only a proxy is set which was not the case in my setup. So this is a first issue.
And then as you rightfully pointed, the Apache HTTP connection pool needs to be configured.

I opened https://github.com/finos/symphony-bdk-java/pull/540 to fix that.
